feat: allow path-based install for Ape (#45)

diff --git a/.github/workflows/test_ape_version.yaml b/.github/workflows/test_ape_version.yaml
--- a/.github/workflows/test_ape_version.yaml
+++ b/.github/workflows/test_ape_version.yaml
@@ -22,9 +22,10 @@ jobs:
         version:
           [
             'default',
-            '0.8.24',
-            '==0.8.24',
+            '0.8.36',
+            '==0.8.36',
             'git+https://github.com/ApeWorX/ape.git@main',
+            '<PATH_TO_APE>',
           ]
         extra-packages: [
           'requirements.txt',
@@ -36,11 +37,29 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
+      # Checkout eth-ape repo if needed for <PATH_TO_APE>
+      - name: Checkout eth-ape
+        if: contains(matrix.version, '<PATH_TO_APE>')
+        uses: actions/checkout@v4
+        with:
+          repository: ApeWorX/ape
+          path: eth-ape
+
+      - name: Debug eth-ape folder
+        if: contains(matrix.version, '<PATH_TO_APE>')
+        run: |
+          echo "Listing current directory"
+          ls -la
+          echo "Listing eth-ape directory"
+          ls -la eth-ape || echo "eth-ape directory not found"
+
       - name: Check version pin
         id: check-version
         run: |
           if [[ "${{ matrix.version }}" == "default" ]]; then
             echo "ape-version=''" >> $GITHUB_OUTPUT
+          elif [[ "${{ matrix.version }}" == "<PATH_TO_APE>" ]]; then
+            echo "ape-version=${{ github.workspace }}/eth-ape" >> $GITHUB_OUTPUT
           else
             echo "ape-version=${{ matrix.version }}" >> $GITHUB_OUTPUT
           fi
@@ -50,7 +69,7 @@ jobs:
         shell: bash
         run: |
           pip install tomlkit
-        python -c 'from pathlib import Path; txt = Path("requirements.txt").read_text(); import tomlkit; print(tomlkit.dumps({"project": {"dependencies": [line for line in txt.splitlines() if not line.startswith("#")], "name":"test", "version": "0.0.0"}}))' | tee pyproject.toml
+          python -c 'from pathlib import Path; txt = Path("requirements.txt").read_text(); import tomlkit; print(tomlkit.dumps({"project": {"dependencies": [line for line in txt.splitlines() if not line.startswith("#")], "name":"test", "version": "0.0.0"}}))' | tee pyproject.toml
           rm requirements.txt
 
       - name: Run ape action
